# Generated by Django 5.0.7 on 2024-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_event', models.CharField(max_length=35)),
                ('time_of_event', models.IntegerField()),
                ('venue_of_event', models.TextField()),
                ('details_of_event', models.TextField()),
            ],
        ),
    ]
