# Generated by Django 5.0.7 on 2024-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
